[pytest]
markers =
    validacion_precio: Prueba para la validación de montos y subtotales en el carrito
    ordenamiento: Mark generado por los tags de BDD

addopts = --html=reporte.html --self-contained-html